export const posts = [
  {
    id: 1,
    title: "Introduction to AI",
    slug: "introduction-to-ai",
    category: "Technology",
    subcategory: "Artificial Intelligence",
    content: "AI is transforming the world in various fields such as healthcare, finance, and more. This post introduces the basics of AI and its applications.",
    date: "2024-01-15",
  },
  {
    id: 2,
    title: "Understanding Machine Learning",
    slug: "understanding-machine-learning",
    category: "Technology",
    subcategory: "Artificial Intelligence",
    content: "Machine learning is a subset of AI. Learn how it enables computers to learn from data and improve over time without being explicitly programmed.",
    date: "2024-02-05",
  },
  {
    id: 3,
    title: "Future of Quantum Computing",
    slug: "future-of-quantum-computing",
    category: "Technology",
    subcategory: "Quantum Computing",
    content: "Quantum computing promises to revolutionize industries by solving complex problems that are impossible for classical computers to handle.",
    date: "2024-03-20",
  },
  {
    id: 4,
    title: "Top 10 JavaScript Frameworks in 2024",
    slug: "top-10-javascript-frameworks-2024",
    category: "Web Development",
    subcategory: "JavaScript",
    content: "JavaScript frameworks have evolved significantly. In this post, we explore the top 10 frameworks you should consider in 2024.",
    date: "2024-04-10",
  },
  {
    id: 5,
    title: "What's New in Next.js 14?",
    slug: "whats-new-in-next-js-14",
    category: "Web Development",
    subcategory: "Next.js",
    content: "Next.js 14 brings exciting features like the new app directory, React Server Components, and more. Learn about what's new in this release.",
    date: "2024-05-01",
  },
  {
    id: 6,
    title: "Building Responsive Websites with Tailwind CSS",
    slug: "building-responsive-websites-with-tailwind",
    category: "Web Development",
    subcategory: "CSS",
    content: "Tailwind CSS allows for rapid styling of responsive websites. Discover how to create mobile-friendly designs using utility-first CSS.",
    date: "2024-05-18",
  },
  {
    id: 7,
    title: "Introduction to Blockchain",
    slug: "introduction-to-blockchain",
    category: "Technology",
    subcategory: "Blockchain",
    content: "Blockchain technology is more than just cryptocurrencies. Learn how it works and its potential to disrupt various industries.",
    date: "2024-06-01",
  },
  {
    id: 8,
    title: "The Rise of Edge Computing",
    slug: "the-rise-of-edge-computing",
    category: "Technology",
    subcategory: "Cloud Computing",
    content: "Edge computing brings data processing closer to the source of data. Learn how it's changing the cloud computing landscape.",
    date: "2024-06-15",
  },
  {
    id: 9,
    title: "Top 5 Frontend Development Tools",
    slug: "top-5-frontend-development-tools",
    category: "Web Development",
    subcategory: "Frontend",
    content: "As a frontend developer, you need the right tools to be productive. Check out the top 5 tools that can enhance your development workflow.",
    date: "2024-07-05",
  },
  {
    id: 10,
    title: "How to Optimize React Apps for Performance",
    slug: "optimize-react-apps-for-performance",
    category: "Web Development",
    subcategory: "React",
    content: "Performance optimization in React apps is crucial for a great user experience. Learn various techniques to speed up your React applications.",
    date: "2024-07-22",
  },
  {
    id: 11,
    title: "The Basics of DevOps",
    slug: "the-basics-of-devops",
    category: "Software Engineering",
    subcategory: "DevOps",
    content: "DevOps bridges the gap between development and operations. This post covers the basics of DevOps and how it's improving software delivery.",
    date: "2024-08-01",
  },
  {
    id: 12,
    title: "Understanding Cloud Native Architecture",
    slug: "understanding-cloud-native-architecture",
    category: "Cloud Computing",
    subcategory: "Architecture",
    content: "Cloud-native architecture allows you to build scalable, resilient applications. Learn how it's different from traditional monolithic systems.",
    date: "2024-08-10",
  },
  {
    id: 13,
    title: "Best Practices for Microservices",
    slug: "best-practices-for-microservices",
    category: "Software Engineering",
    subcategory: "Microservices",
    content: "Microservices architecture helps scale and manage applications more efficiently. Explore the best practices for implementing microservices.",
    date: "2024-09-01",
  },
  {
    id: 14,
    title: "5 Key Trends in Cybersecurity",
    slug: "5-key-trends-in-cybersecurity",
    category: "Technology",
    subcategory: "Cybersecurity",
    content: "Cybersecurity is constantly evolving. Stay ahead of the curve by learning about the top trends shaping the cybersecurity landscape in 2024.",
    date: "2024-09-10",
  },
  {
    id: 15,
    title: "A Guide to Serverless Computing",
    slug: "guide-to-serverless-computing",
    category: "Cloud Computing",
    subcategory: "Serverless",
    content: "Serverless computing allows developers to build applications without managing servers. Learn how this model works and its benefits.",
    date: "2024-09-25",
  },
  {
    id: 16,
    title: "The Future of 5G Technology",
    slug: "future-of-5g-technology",
    category: "Technology",
    subcategory: "5G",
    content: "5G technology is revolutionizing mobile networks and communication. Explore how it's going to impact industries and daily life.",
    date: "2024-10-01",
  },
  {
    id: 17,
    title: "Introduction to GraphQL for APIs",
    slug: "introduction-to-graphql",
    category: "Web Development",
    subcategory: "APIs",
    content: "GraphQL offers a more flexible alternative to REST APIs. Learn how GraphQL can simplify API development and improve performance.",
    date: "2024-10-10",
  },
  {
    id: 18,
    title: "Top 10 Programming Languages in 2024",
    slug: "top-10-programming-languages-2024",
    category: "Software Engineering",
    subcategory: "Programming Languages",
    content: "Stay ahead in the tech industry by learning about the top 10 programming languages in 2024 and their use cases.",
    date: "2024-10-12",
  },
  {
    id: 19,
    title: "How to Build Scalable Web Apps",
    slug: "build-scalable-web-apps",
    category: "Web Development",
    subcategory: "Architecture",
    content: "Building scalable web applications is essential for handling large amounts of traffic. Learn about the key principles for scalability.",
    date: "2024-10-14",
  },
  {
    id: 20,
    title: "Exploring IoT in Smart Homes",
    slug: "exploring-iot-in-smart-homes",
    category: "Technology",
    subcategory: "IoT",
    content: "The Internet of Things (IoT) is making smart homes more connected than ever. Discover the latest developments in smart home technology.",
    date: "2024-10-18",
  },
];
